Jupyter notebook for inspecting pandas dataframes

In [1]:
import sys
sys.path.append('/home/ppxjd3/Code')

import numpy as np
import matplotlib.pyplot as plt

from ParticleTracking import dataframes
from Generic import filedialogs

Load data

In [2]:
file = filedialogs.load_filename('Load a dataframe', 
                                 '/media/data/Data',
                                 '*.hdf5')
data = dataframes.DataStore(file)

Memory usage

In [60]:
data.df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70586907 entries, 0 to 30095
Data columns (total 14 columns):
x               int32
y               int32
r               int32
particle        int64
Duty            uint16
order_r         float32
order_i         float32
order_mag       float32
neighbors       uint8
order_mean      float32
order_sus       float32
density         float32
shape_factor    float32
on_edge         bool
dtypes: bool(1), float32(7), int32(3), int64(1), uint16(1), uint8(1)
memory usage: 4.0 GB

In [7]:
data.df.memory_usage(deep=True)

Index           564695256
x               282347628
y               282347628
r               282347628
particle        564695256
Duty            141173814
order_r         282347628
order_i         282347628
order_mag       282347628
neighbors        70586907
order_mean      282347628
order_sus       282347628
density         282347628
shape_factor    282347628
on_edge          70586907
dtype: int64

In [63]:
df = data.df
df1 = df.loc[:10].copy()

In [67]:
import pandas as pd
df1.tail()

,x,y,r,particle,Duty,order_r,order_i,order_mag,neighbors,order_mean,order_sus,density,shape_factor,on_edge
frame,,,,,,,,,,,,,,
10,796,1240,13,2028,400,0.946835,-0.018640,0.947018,6,0.950091,0.00608,2711.701172,1.106171,False
10,799,81,13,1185,400,0.977535,-0.075500,0.980446,6,0.950091,0.00608,2521.926514,1.103698,False
10,808,1053,13,1545,400,0.974744,-0.042187,0.975657,6,0.950091,0.00608,2659.954102,1.105601,False
10,811,1431,13,2069,400,0.942721,-0.098885,0.947893,6,0.950091,0.00608,2598.272461,1.105180,False
10,762,864,13,2185,400,0.972845,0.016908,0.972992,6,0.950091,0.00608,2641.754639,1.106246,False

In [70]:
df = df.reset_index()
df.head()

,frame,x,y,r,particle,Duty,order_r,order_i,order_mag,neighbors,order_mean,order_sus,density,shape_factor,on_edge
0,0,588,840,13,0,400,0.966493,0.045674,0.967572,6,0.947826,0.00797,2555.444824,1.104924,False
1,0,260,598,13,1,400,0.947087,0.102668,0.952635,6,0.947826,0.00797,2774.092529,1.104882,False
2,0,297,1245,13,2,400,0.965628,-0.051430,0.966996,4,0.947826,0.00797,1911.230347,1.203040,True
3,0,303,409,13,3,400,0.951674,-0.116993,0.958838,6,0.947826,0.00797,2771.345703,1.105087,False
4,0,307,517,13,4,400,0.905090,-0.172186,0.921323,6,0.947826,0.00797,2632.599609,1.107951,False

In [71]:
df = df.set_index('frame')

In [72]:
df.head()

,x,y,r,particle,Duty,order_r,order_i,order_mag,neighbors,order_mean,order_sus,density,shape_factor,on_edge
frame,,,,,,,,,,,,,,
0,588,840,13,0,400,0.966493,0.045674,0.967572,6,0.947826,0.00797,2555.444824,1.104924,False
0,260,598,13,1,400,0.947087,0.102668,0.952635,6,0.947826,0.00797,2774.092529,1.104882,False
0,297,1245,13,2,400,0.965628,-0.051430,0.966996,4,0.947826,0.00797,1911.230347,1.203040,True
0,303,409,13,3,400,0.951674,-0.116993,0.958838,6,0.947826,0.00797,2771.345703,1.105087,False
0,307,517,13,4,400,0.905090,-0.172186,0.921323,6,0.947826,0.00797,2632.599609,1.107951,False

In [73]:
df['test'] = 1
df.head()

,x,y,r,particle,Duty,order_r,order_i,order_mag,neighbors,order_mean,order_sus,density,shape_factor,on_edge,test
frame,,,,,,,,,,,,,,,
0,588,840,13,0,400,0.966493,0.045674,0.967572,6,0.947826,0.00797,2555.444824,1.104924,False,1
0,260,598,13,1,400,0.947087,0.102668,0.952635,6,0.947826,0.00797,2774.092529,1.104882,False,1
0,297,1245,13,2,400,0.965628,-0.051430,0.966996,4,0.947826,0.00797,1911.230347,1.203040,True,1
0,303,409,13,3,400,0.951674,-0.116993,0.958838,6,0.947826,0.00797,2771.345703,1.105087,False,1
0,307,517,13,4,400,0.905090,-0.172186,0.921323,6,0.947826,0.00797,2632.599609,1.107951,False,1

In [74]:
df1 = df.loc[:10].copy()

In [92]:
data = pd.Series(np.arange(11), index=pd.RangeIndex(0, 11, name='frame'))
df1['test'] = data

                   x     y     r  Duty  order_r  order_i  order_mag  \
frame particle
0     0         True  True  True  True     True     True       True
      1         True  True  True  True     True     True       True
      2         True  True  True  True     True     True       True
      3         True  True  True  True     True     True       True
      4         True  True  True  True     True     True       True
      5         True  True  True  True     True     True       True
      6         True  True  True  True     True     True       True
      7         True  True  True  True     True     True       True
      8         True  True  True  True     True     True       True
      9         True  True  True  True     True     True       True
      10        True  True  True  True     True     True       True
      11        True  True  True  True     True     True       True
      12        True  True  True  True     True     True       True
      13        True  True  True  True     True     True       True
      14        True  True  True  True     True     True       True
      15        True  True  True  True     True     True       True
      16        True  True  True  True     True     True       True
      17        True  True  True  True     True     True       True
      18        True  True  True  True     True     True       True
      19        True  True  True  True     True     True       True
      20        True  True  True  True     True     True       True
      21        True  True  True  True     True     True       True
      22        True  True  True  True     True     True       True
      23        True  True  True  True     True     True       True
      24        True  True  True  True     True     True       True
      25        True  True  True  True     True     True       True
      26        True  True  True  True     True     True       True
      27        True  True  True  True     True     True       True
      28        True  True  True  True     True     True       True
      29        True  True  True  True     True     True       True
...              ...   ...   ...   ...      ...      ...        ...
10    2472      True  True  True  True     True     True       True
      2476      True  True  True  True     True     True       True
      2480      True  True  True  True     True     True       True
      2483      True  True  True  True     True     True       True
      2495      True  True  True  True     True     True       True
      2503      True  True  True  True     True     True       True
      2504      True  True  True  True     True     True       True
      2505      True  True  True  True     True     True       True
      2507      True  True  True  True     True     True       True
      2511      True  True  True  True     True     True       True
      2514      True  True  True  True     True     True       True
      2530      True  True  True  True     True     True       True
      2534      True  True  True  True     True     True       True
      2539      True  True  True  True     True     True       True
      2548      True  True  True  True     True     True       True
      2549      True  True  True  True     True     True       True
      2556      True  True  True  True     True     True       True
      2560      True  True  True  True     True     True       True
      2563      True  True  True  True     True     True       True
      2565      True  True  True  True     True     True       True
      2575      True  True  True  True     True     True       True
      2579      True  True  True  True     True     True       True
      2584      True  True  True  True     True     True       True
      2587      True  True  True  True     True     True       True
      2598      True  True  True  True     True     True       True
      2599      True  True  True  True     True     True       True
      2603      True  True  True  True     True     True       True
      2604      True  True  True  True     True     True       True
      2606      True  True  True  True     True     True       True
      2612      True  True  True  True     True     True       True

                neighbors  order_mean  order_sus  density  shape_factor  \
frame particle
0     0              True        True       True     True          True
      1              True        True       True     True          True
      2              True        True       True     True          True
      3              True        True       True     True          True
      4              True        True       True     True          True
      5              True        True       True     True          True
      6              True        True       True     True          True
      7              True        True       True     True          True
      8              True        True       True     True          True
      9              True        True       True     True          True
      10             True        True       True     True          True
      11             True        True       True     True          True
      12             True        True       True     True          True
      13             True        True       True     True          True
      14             True        True       True     True          True
      15             True        True       True     True          True
      16             True        True       True     True          True
      17             True        True       True     True          True
      18             True        True       True     True          True
      19             True        True       True     True          True
      20             True        True       True     True          True
      21             True        True       True     True          True
      22             True        True       True     True          True
      23             True        True       True     True          True
      24             True        True       True     True          True
      25             True        True       True     True          True
      26             True        True       True     True          True
      27             True        True       True     True          True
      28             True        True       True     True          True
      29             True        True       True     True          True
...                   ...         ...        ...      ...           ...
10    2472           True        True       True     True          True
      2476           True        True       True     True          True
      2480           True        True       True     True          True
      2483           True        True       True     True          True
      2495           True        True       True     True          True
      2503           True        True       True     True          True
      2504           True        True       True     True          True
      2505           True        True       True     True          True
      2507           True        True       True     True          True
      2511           True        True       True     True          True
      2514           True        True       True     True          True
      2530           True        True       True     True          True
      2534           True        True       True     True          True
      2539           True        True       True     True          True
      2548           True        True       True     True          True
      2549           True        True       True     True          True
      2556           True        True       True     True          True
      2560           True        True       True     True          True
      2563           True        True       True     True          True
      2565           True        True       True     True          True
      2575           True        True       True     True          True
      2579           True        True       True     True          True
      2584           True        True       True     True          True
      2587           True        True       True     True          True
      2598           True        True       True     True          True
      2599           True        True       True     True          True
      2603           True        True       True     True          True
      2604           True        True       True     True          True
      2606           True        True       True     True          True
      2612           True        True       True     True          True

                on_edge   test
frame particle
0     0           False  False
      1           False  False
      2            True  False
      3           False  False
      4           False  False
      5           False  False
      6           False  False
      7           False  False
      8            True  False
      9            True  False
      10          False  False
      11          False  False
      12          False  False
      13          False  False
      14          False  False
      15          False  False
      16          False  False
      17          False  False
      18          False  False
      19           True  False
      20          False  False
      21          False  False
      22          False  False
      23          False  False
      24          False  False
      25           True  False
      26          False  False
      27          False  False
      28           True  False
      29          False  False
...                 ...    ...
10    2472         True   True
      2476         True   True
      2480        False   True
      2483         True   True
      2495        False   True
      2503         True   True
      2504         True   True
      2505         True   True
      2507         True   True
      2511        False   True
      2514         True   True
      2530         True   True
      2534        False   True
      2539         True   True
      2548         True   True
      2549         True   True
      2556         True   True
      2560         True   True
      2563        False   True
      2565         True   True
      2575         True   True
      2579        False   True
      2584         True   True
      2587         True   True
      2598         True   True
      2599         True   True
      2603         True   True
      2604         True   True
      2606         True   True
      2612         True   True

[26578 rows x 14 columns]

In [4]:
data.df.reset_index().set_index(['frame', 'Duty', ]).info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 70586907 entries, (0, 400, 0) to (30095, 1000, 2423603)
Data columns (total 12 columns):
x               int32
y               int32
r               int32
order_r         float32
order_i         float32
order_mag       float32
neighbors       uint8
order_mean      float32
order_sus       float32
density         float32
shape_factor    float32
on_edge         bool
dtypes: bool(1), float32(7), int32(3), uint8(1)
memory usage: 3.3 GB

In [14]:
df1 = data.df

In [22]:
test_data = np.unique(df1.index.values)

In [19]:
test_data = np.arange(30096)

In [26]:
test_data

array([    0,     1,     2, ..., 30093, 30094, 30095])